openapi: 3.0.0
info:
  title: Locatitude API
  description: | 
    This API provides the following 
    * Latitude and Longitude of the visited location
    * PM 2.5 of the visited location
    * Population in the visited location
    * Number of Covid 19 cases near the visited location
    * Covid19 trend for each province
    * PM2.5 trend for each province
    * Infection rate of 1 million people per day for each province
  version: 1.0.0
servers:
- url: /locatitude
paths:
  /latlong/{date}:
    parameters:
    - name: date
      in: path
      required: true
      schema:
        type: string
        format: date
    get:
      summary: Returns the latitude and longitude of a specific date
      operationId: controller.get_lat_long
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LatLong'
  /pm/{date}:
      parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
      get:
        summary: Returns the PM2.5 of a specific date
        operationId: controller.get_pm
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/PM25'
  /province/{date}:
      parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date
      get:
        summary: Returns the province of a specific date
        operationId: controller.get_province
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Province'
  /population/{province}:
      parameters:
      - name: province
        in: path
        required: true
        schema:
          type: string
      get:
        summary: Returns the population of a province
        operationId: controller.get_population
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Population'
  /covid/{date}:
      parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
      get:
        summary: Returns the covid19 cases of a specific date
        operationId: controller.get_covid19
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Covid19'
  /population/allprovinces:
      get:
        summary: Returns the population of all the provinces
        operationId: controller.get_provinces_population
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Population'
  /covid/trend/:
      get:
        summary: Returns the covid19 trend
        operationId: controller.get_covid19_trend
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/CovidTrend'
  /covid/sum/:
      get:
        summary: Returns the sum of the new covid cases in each province.
        operationId: controller.get_sum_covid19
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/SumCovid' 
  /pm/trend/:
      get:
        summary: Returns the PM2.5 trend
        operationId: controller.get_pm_trend
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/PmTrend'
  /covid/new/eachday/:
    get:
      summary: Returns the new covid cases of each day
      operationId: controller.get_new_covid19_each_day
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewCovidEachDay'
  /pm/eachday/:
    get:
      summary: Returns the PM2.5 of each day
      operationId: controller.get_pm_each_day
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PM25'
  /showall/:
    get:
      summary: Returns all the information of each day
      operationId: controller.get_show_all
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AllDetails'

components:
  schemas:
    LatLong:
      type: object
      properties:
        timeStamp:
          type: string
        lat:
          type: number
        long:
          type: number
    PM25:
      type: object
      properties:
        timeStamp:
          type: string
        pm:
          type: integer
    Province:
      type: object
      properties:
        timeStamp:
          type: string
        province:
          type: string 
    Population:
      type: object
      properties:
        province:
          type: string
        population:
          type: integer
    Covid19:
      type: object
      properties:
        timeStamp:
          type: string
        newcovid:
          type: integer
        totalcovid:
          type: integer 
    CovidTrend:
      type: object
      properties:
        province:
          type: string
        population:
          type: integer
        AvgCovid:
          type: number
    PmTrend:
      type: object
      properties:
        province:
          type: string
        population:
          type: integer
        AvgPM:
          type: number
    SumCovid:
      type: object
      properties:
        province:
          type: string
        population:
          type: integer
        sumcovid:
          type: integer
    NewCovidEachDay:
      type: object
      properties:
        timeStamp:
          type: string
        newcovid:
          type: integer
    AllDetails:
      type: object
      properties:
        timeStamp:
          type: string
        lat:
          type: number
        long:
          type: number
        province:
          type: string
        population:
          type: integer
        pm:
          type: integer
        newcovid:
          type: integer
        totalcovid:
          type: integer 
    