# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class NewCovidEachDay(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time_stamp=None, newcovid=None):  # noqa: E501
        """NewCovidEachDay - a model defined in OpenAPI

        :param time_stamp: The time_stamp of this NewCovidEachDay.  # noqa: E501
        :type time_stamp: str
        :param newcovid: The newcovid of this NewCovidEachDay.  # noqa: E501
        :type newcovid: int
        """
        self.openapi_types = {
            'time_stamp': str,
            'newcovid': int
        }

        self.attribute_map = {
            'time_stamp': 'timeStamp',
            'newcovid': 'newcovid'
        }

        self._time_stamp = time_stamp
        self._newcovid = newcovid

    @classmethod
    def from_dict(cls, dikt) -> 'NewCovidEachDay':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewCovidEachDay of this NewCovidEachDay.  # noqa: E501
        :rtype: NewCovidEachDay
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_stamp(self):
        """Gets the time_stamp of this NewCovidEachDay.


        :return: The time_stamp of this NewCovidEachDay.
        :rtype: str
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this NewCovidEachDay.


        :param time_stamp: The time_stamp of this NewCovidEachDay.
        :type time_stamp: str
        """

        self._time_stamp = time_stamp

    @property
    def newcovid(self):
        """Gets the newcovid of this NewCovidEachDay.


        :return: The newcovid of this NewCovidEachDay.
        :rtype: int
        """
        return self._newcovid

    @newcovid.setter
    def newcovid(self, newcovid):
        """Sets the newcovid of this NewCovidEachDay.


        :param newcovid: The newcovid of this NewCovidEachDay.
        :type newcovid: int
        """

        self._newcovid = newcovid
