# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PM25(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time_stamp=None, pm=None):  # noqa: E501
        """PM25 - a model defined in OpenAPI

        :param time_stamp: The time_stamp of this PM25.  # noqa: E501
        :type time_stamp: str
        :param pm: The pm of this PM25.  # noqa: E501
        :type pm: int
        """
        self.openapi_types = {
            'time_stamp': str,
            'pm': int
        }

        self.attribute_map = {
            'time_stamp': 'timeStamp',
            'pm': 'pm'
        }

        self._time_stamp = time_stamp
        self._pm = pm

    @classmethod
    def from_dict(cls, dikt) -> 'PM25':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PM25 of this PM25.  # noqa: E501
        :rtype: PM25
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_stamp(self):
        """Gets the time_stamp of this PM25.


        :return: The time_stamp of this PM25.
        :rtype: str
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this PM25.


        :param time_stamp: The time_stamp of this PM25.
        :type time_stamp: str
        """

        self._time_stamp = time_stamp

    @property
    def pm(self):
        """Gets the pm of this PM25.


        :return: The pm of this PM25.
        :rtype: int
        """
        return self._pm

    @pm.setter
    def pm(self, pm):
        """Sets the pm of this PM25.


        :param pm: The pm of this PM25.
        :type pm: int
        """

        self._pm = pm
