# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Population(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, province=None, population=None):  # noqa: E501
        """Population - a model defined in OpenAPI

        :param province: The province of this Population.  # noqa: E501
        :type province: str
        :param population: The population of this Population.  # noqa: E501
        :type population: int
        """
        self.openapi_types = {
            'province': str,
            'population': int
        }

        self.attribute_map = {
            'province': 'province',
            'population': 'population'
        }

        self._province = province
        self._population = population

    @classmethod
    def from_dict(cls, dikt) -> 'Population':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Population of this Population.  # noqa: E501
        :rtype: Population
        """
        return util.deserialize_model(dikt, cls)

    @property
    def province(self):
        """Gets the province of this Population.


        :return: The province of this Population.
        :rtype: str
        """
        return self._province

    @province.setter
    def province(self, province):
        """Sets the province of this Population.


        :param province: The province of this Population.
        :type province: str
        """

        self._province = province

    @property
    def population(self):
        """Gets the population of this Population.


        :return: The population of this Population.
        :rtype: int
        """
        return self._population

    @population.setter
    def population(self, population):
        """Sets the population of this Population.


        :param population: The population of this Population.
        :type population: int
        """

        self._population = population
