# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Province(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time_stamp=None, province=None):  # noqa: E501
        """Province - a model defined in OpenAPI

        :param time_stamp: The time_stamp of this Province.  # noqa: E501
        :type time_stamp: str
        :param province: The province of this Province.  # noqa: E501
        :type province: str
        """
        self.openapi_types = {
            'time_stamp': str,
            'province': str
        }

        self.attribute_map = {
            'time_stamp': 'timeStamp',
            'province': 'province'
        }

        self._time_stamp = time_stamp
        self._province = province

    @classmethod
    def from_dict(cls, dikt) -> 'Province':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Province of this Province.  # noqa: E501
        :rtype: Province
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_stamp(self):
        """Gets the time_stamp of this Province.


        :return: The time_stamp of this Province.
        :rtype: str
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this Province.


        :param time_stamp: The time_stamp of this Province.
        :type time_stamp: str
        """

        self._time_stamp = time_stamp

    @property
    def province(self):
        """Gets the province of this Province.


        :return: The province of this Province.
        :rtype: str
        """
        return self._province

    @province.setter
    def province(self, province):
        """Sets the province of this Province.


        :param province: The province of this Province.
        :type province: str
        """

        self._province = province
