# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class SumCovid(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, province=None, population=None, sumcovid=None):  # noqa: E501
        """SumCovid - a model defined in OpenAPI

        :param province: The province of this SumCovid.  # noqa: E501
        :type province: str
        :param population: The population of this SumCovid.  # noqa: E501
        :type population: int
        :param sumcovid: The sumcovid of this SumCovid.  # noqa: E501
        :type sumcovid: int
        """
        self.openapi_types = {
            'province': str,
            'population': int,
            'sumcovid': int
        }

        self.attribute_map = {
            'province': 'province',
            'population': 'population',
            'sumcovid': 'sumcovid'
        }

        self._province = province
        self._population = population
        self._sumcovid = sumcovid

    @classmethod
    def from_dict(cls, dikt) -> 'SumCovid':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SumCovid of this SumCovid.  # noqa: E501
        :rtype: SumCovid
        """
        return util.deserialize_model(dikt, cls)

    @property
    def province(self):
        """Gets the province of this SumCovid.


        :return: The province of this SumCovid.
        :rtype: str
        """
        return self._province

    @province.setter
    def province(self, province):
        """Sets the province of this SumCovid.


        :param province: The province of this SumCovid.
        :type province: str
        """

        self._province = province

    @property
    def population(self):
        """Gets the population of this SumCovid.


        :return: The population of this SumCovid.
        :rtype: int
        """
        return self._population

    @population.setter
    def population(self, population):
        """Sets the population of this SumCovid.


        :param population: The population of this SumCovid.
        :type population: int
        """

        self._population = population

    @property
    def sumcovid(self):
        """Gets the sumcovid of this SumCovid.


        :return: The sumcovid of this SumCovid.
        :rtype: int
        """
        return self._sumcovid

    @sumcovid.setter
    def sumcovid(self, sumcovid):
        """Sets the sumcovid of this SumCovid.


        :param sumcovid: The sumcovid of this SumCovid.
        :type sumcovid: int
        """

        self._sumcovid = sumcovid
